### PR TITLE
Towards 0.2 for QTCS

### PR DESCRIPTION
**Pull request by cdondrup**
This uses the new structure for QTCs.

I also made two changes to the qsr_abstractclass:
1. I pass `**kwargs` to `make_world_qsr_trace` this is necessary to then pass it to `_process_qsrs_for` which would otherwise always return an empty dict as it does not get the dynamic_args otherwise (judging from your mos example at least).
2. I commented line 114 because in QTC you marked `custom_checks_for_qsrs_for` as deprecated and not needed but then you call it regardless. This only happens when `qsrs_for` are created by the lib instead of passed so without the previous change this would have never been called.

### CODE REVIEW

**Comment by cdondrup** [comment]
OK, you apparently changed in the mean time... Let me rebase this and resolve the conflicts.

**Comment by gatsoulis** [comment]
Wait one sec

**Comment by gatsoulis** [comment]
OK, rebase from this please. The two changes are:
- `make_world_qsr_trace` prototype slightly changed (basically not passing the whole kwargs again)
- similarly for `_postprocess_world_qsr_trace`

Sorry about that.

**Comment by cdondrup** [comment]
OK, you fixed all the stuff. I'll close this and open another one, cherry-picking my commits and adjusting to the new changes.

**Comment by gatsoulis** [comment]
Mind one sec before you go ahead. Need your views on something.

**Comment by cdondrup** [comment]
OK

**Comment by gatsoulis** [comment]
On the comment above I changed so the whole kwargs (i.e. req_params) is not passed to some functions, thinking it might be a memory and speed improvement (the `input_data` ie the whole world_trace is bounced around` + clarity. Hoeever, on second thought recalling python passes by reference so probably there is no speed/memory improvements, I think. From your point what do you think?

As such, which one of the two do you prefer? Old style passing the whole kwargs or simply passing what is needed.

**Comment by gatsoulis** [comment]
[Relavant line](https://github.com/yianni/strands_qsr_lib/blob/towards-0.2/qsr_lib/src/qsrlib_qsrs/qsr_abstractclass.py#L64)

**Comment by cdondrup** [comment]
Since you do with qsr_params what ever you like as they are created from the kwargs directly, I think just passing them would be enough. The only problem I see is with the qsrs_for creation as they need the dynamic args unaltered to make sure that the qsrs_for entry is in there. I don't mind passing kwargs as it gives you more freedom as well, but if you have a better idea of handling the qsrs_for then I'm happy with just using qsr_params.

**Comment by gatsoulis** [comment]
Hmmm, OK need to revert back then I think and pass the whole kwargs. Will need a bit of time for this as I will need to check the qsrs_for also. Will let you know when and you can rebase and PR.

**Comment by cdondrup** [comment]
OK

**Comment by gatsoulis** [comment]
Reverted. Free to rebase.

**Pull request closed without merging**
