### PR TITLE
Adjusting QTC to new structure

### PR DESCRIPTION
**Pull request by cdondrup**
Also adjusting and creating new tests.

### CODE REVIEW

**Comment by gatsoulis** [comment]
Is this the latest PR?

**Comment by cdondrup** [comment]
Yes, it was :)

**Comment by gatsoulis** [comment]
OK... looking through it. Have some questions/comments. Will post them promptly.

**Comment by gatsoulis** [comment]
Cool. Looks fine. Just deleted most of the deprecated functions. 

Had one comment about In `_process_qsr_parameters_from_request_parameters` where global namespace seemed to be taking preceedence but I see you overwrite these values with the qsr namespace later.

Such assignments might be dangerous as they allow the user for typos and won't give any warning; but let them be for now. 

``` python
for k, v in req_params["dynamic_args"]["for_all_qsrs"].items():
                    qsr_params[k] = v
```

I will add a check in the end. Can you confirm that the only parameters are the following or are there more?

``` python
"quantisation_factor": 0.0,
            "validate": True,
            "no_collapse": False,
            "distance_threshold": 1.22
```

**Comment by cdondrup** [comment]
True, the typo thing should be fixed...

Yes, those are the only parameters.

**Pull request merged**
