### PR TITLE
QTC had problems when there was only one QTC state in the chain and would error

### PR DESCRIPTION
**Pull request by cdondrup**
This fixes it.

### CODE REVIEW

**Comment by gatsoulis** [comment]
Hmmm, not getting email notifications when there is a PR here.... Is this fixing QTCS issues mentioned in my PR?

**Comment by gatsoulis** [comment]
I take it yes... Apparently owner has to click on watch to get notification on their own repos. _doh_

**Comment by cdondrup** [comment]
Good to know... stupid github

**Comment by gatsoulis** [comment]
Might be because I have opted out to watch by default new repositories, although hoped this does not apply to mine.

**Pull request merged**
